### ISSUE TITLE
Failure in running Clone&Play DESI survey simulation sample

### ISSUE THREAD

**Issue by rncahn** [desihub/quicksurvey_example#17]
Example given in Clone&Play failed.  

 File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2630, in _extract_colnum
    colnum = self._colnames_lower.index(colstr.lower())
ValueError: 'true_mag_r_sdss_nodust' is not in list

And finally

 File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2632, in _extract_colnum
    raise ValueError(mess)
ValueError: column name 'TRUE_MAG_R_SDSS_NODUST' not found (case insensitive)
rncahn@cori04:/global/cscratch1/sd/rncahn/quicksurvey_example> join_mock_targets --mockdir $SCRATCH/quicksurvey_example/targets/no_spectra/dark
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension SKY. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension STD. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension STD. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension TARGETS. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension TRUTH. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension TRUTH_BGS. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension TRUTH_ELG. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension TRUTH_LRG. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension TRUTH_QSO. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension TRUTH_STAR. Skipping.
INFO:build.py:1211:_merge_file_tables: Zero pixel files for extension TRUTH_WD. Skipping.
INFO:build.py:1355:join_targets_truth: Generating merged target list /global/cscratch1/sd/rncahn/quicksurvey_example/targets/no_spectra/dark/mtl.fits
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.27.0/bin/join_mock_targets", line 4, in <module>
    __import__('pkg_resources').run_script('desitarget==0.27.0', 'join_mock_targets')
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.27.0/lib/python3.6/site-packages/desitarget-0.27.0-py3.6.egg/EGG-INFO/scripts/join_mock_targets", line 33, in <module>
    join_targets_truth(args.mockdir, outdir=args.outdir, overwrite=args.overwrite, comm=comm)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.27.0/lib/python3.6/site-packages/desitarget-0.27.0-py3.6.egg/desitarget/mock/build.py", line 1356, in join_targets_truth
    targets = fitsio.read(outdir+'/targets.fits')
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 87, in read
    with FITS(filename, **keys) as fits:
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 351, in __init__
    raise IOError("File not found: '%s'" % filename)
OSError: File not found: '/global/cscratch1/sd/rncahn/quicksurvey_example/targets/no_spectra/dark/targets.fits'

**Comment by sbailey** [comment]
@moustakas do you recognize `TRUE_MAG_R_SDSS_NODUST`?

@forero mentioning you to get this onto your radar (I didn't get an automated email about this ticket from this repo, so you probably didn't either).

**Comment by moustakas** [comment]
The `Clone&Play` example which calls `select_mock_targets` is using an outdated yaml configuration file.  The latest file (example) file is [here](https://github.com/desihub/desitarget/blob/master/py/desitarget/mock/data/select-mock-targets.yaml).

**Comment by forero** [comment]
I've just tested the current version of the yaml files in this repository with the latest `select_mock_targets` and its works fine. Reading Bob's message the problem seems to be that he is using an old version of `desitarget` (`desiconda/20180709`).

**Comment by forero** [comment]
There is only a minor update to make for the path to the galaxia mocks.  That's unrelated to the issue opened by Bob.

**Comment by forero** [comment]
Sorry, Bob is indeed using `desitarget/0.27.0` (i.e. the latest desitarget).

**Comment by forero** [comment]
The problem was using as an input old MWS mock files that didn't have the field `TRUE_MAG_R_SDSS_NODUST`.

**Comment by moustakas** [comment]
> The problem was using as an input old MWS mock files that didn't have the field TRUE_MAG_R_SDSS_NODUST.

Sorry for not being clear--that's what I meant that the `yaml` configuration file needed to be updated.  The data model of the mock changed in a non backwards-compatible way, and so did the code.

**Comment by rncahn** [comment]
Thanks,guys!
